WINDOW_TITLE = "Wargaiming Test Task"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

RECT_HEIGHT = 30
RECT_WIDTH = RECT_HEIGHT * 2

POINT_INTERSECTION_THRESHOLD = 0.1

QTREE_NODE_CAPACITY = 4


class ActionType:
    DRAG_RECT = 'DRAG_RECT'
    CREATE_REF_LINE = 'CREATE_REF_LINE'
    DELETE_REF_LINE = 'DELETE_REF_LINE'

